# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-04 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conveyer2firstr',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('stamp', models.DateTimeField()),
                ('predstop', models.FloatField()),
                ('predempty', models.FloatField()),
                ('predfull', models.FloatField()),
                ('img', models.TextField()),
                ('idnext', models.UUIDField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='conveyer2next',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nclass', models.IntegerField()),
                ('predict0', models.FloatField()),
                ('predict1', models.FloatField()),
                ('predict2', models.FloatField()),
                ('predict3', models.FloatField()),
                ('predict4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='conveyer2status',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tstamp', models.DateTimeField()),
                ('empty', models.FloatField()),
                ('imerror', models.FloatField()),
                ('full', models.FloatField()),
                ('snn1', models.TextField()),
                ('snn2', models.TextField()),
                ('snn3', models.TextField()),
                ('snnclass', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='convstat',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nclass', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
    ]
