# Generated by Django 2.1.3 on 2018-11-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conv2seconds',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nclass', models.IntegerField()),
                ('ndate', models.DateTimeField()),
                ('seconds', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='conveyer2firstr',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('stamp', models.DateTimeField()),
                ('predstop', models.FloatField()),
                ('predempty', models.FloatField()),
                ('predfull', models.FloatField()),
                ('img', models.TextField()),
                ('idnext', models.UUIDField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='conveyer2imgcrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstamp', models.DateTimeField()),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y1', models.FloatField()),
                ('y2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='conveyer2next',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nclass', models.IntegerField()),
                ('predict0', models.FloatField()),
                ('predict1', models.FloatField()),
                ('predict2', models.FloatField()),
                ('predict3', models.FloatField()),
                ('predict4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='conveyer2status',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tstamp', models.DateTimeField()),
                ('stop', models.FloatField()),
                ('empty', models.FloatField()),
                ('imerror', models.FloatField()),
                ('full', models.FloatField()),
                ('snn1', models.TextField()),
                ('snn2', models.TextField()),
                ('snn3', models.TextField()),
                ('snnclass', models.FloatField()),
                ('img', models.TextField()),
                ('tfile', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='convstat',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nclass', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
    ]
