# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-05 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aik2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conveyer2imgcrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstamp', models.DateTimeField()),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y1', models.FloatField()),
                ('y2', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='conveyer2status',
            name='img',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conveyer2status',
            name='stop',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conveyer2status',
            name='tfile',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
