# Generated by Django 2.1.3 on 2018-11-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aik2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sesgraph',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('sdate', models.DateTimeField()),
                ('ses1', models.FloatField()),
                ('ses2', models.FloatField()),
                ('ses3', models.FloatField()),
                ('ses4', models.FloatField()),
                ('ses5', models.FloatField()),
            ],
        ),
    ]
