# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-24 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aik2', '0002_auto_20180605_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='conv2seconds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nclass', models.IntegerField()),
                ('ndate', models.DateTimeField()),
                ('seconds', models.FloatField()),
            ],
        ),
    ]
